pipeline {
  agent any

  environment {
    WORKLOAD_IP = "18.134.16.172"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'git@github.com:vicky-s-cloud-projects/aws-enterprise-landing-zone.git'
      }
    }

    stage('Terraform Format') {
      steps {
        sh '''
          cd terraform
          terraform fmt -check -recursive
        '''
      }
    }

    stage('Terraform Validate') {
      steps {
        sh '''
          cd terraform
          terraform init -backend=false
          terraform validate
        '''
      }
    }

    stage('Terraform Security Scan (Checkov)') {
      steps {
        sh '''
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install checkov

          cd terraform
          checkov -d . \
            --framework terraform \
            --download-external-modules true \
            --skip-check CKV_AWS_23,CKV2_AWS_62,CKV2_AWS_61,CKV_AWS_18,CKV_AWS_144,CKV_AWS_145 \
            --hard-fail-on HIGH
          '''
      }
    }


    stage('Copy Files to EC2') {
      steps {
        sshagent(['ec2-deploy-key']) {
          sh """
          scp -o StrictHostKeyChecking=no -r docker-compose.yml src ec2-user@${WORKLOAD_IP}:/home/ec2-user/
          """
        }
      }
    }

    stage('Deploy App') {
      steps {
        sshagent(['ec2-deploy-key']) {
          sh """
          ssh -o StrictHostKeyChecking=no ec2-user@${WORKLOAD_IP} '
            cd /home/ec2-user &&
            docker-compose down || true &&
            docker-compose up -d
          '
          """
        }
      }
    }
  }
}


